config/routes.rb
Rails.application.routes.draw do
  get "/search", to:"searches#search", as:"search"
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users, :controllers => {
  	:registrations => "users/registrations"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root :to => "homes#top"
get "home/about" => "homes#about"

resources :books do
	resources :books_comments,only: [:create,:destroy,:edit,:update]
	resource :favorites,only: [:create,:destroy]
end
resources :users do
	resource :relationships, only: [:create,:destroy]
	# 下記の２行はいつも通りの記述でも可
	get :follows, on: :member
	get :followers, on: :member
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :send_welcome_mail

  def send_welcome_mail
    ThanksMailer.user_welcome_mail(self).deliver
  end

  has_many :books,dependent: :destroy
  has_many :books_comments,dependent: :destroy
  has_many :favorites,dependent: :destroy




# 自分がフォローしているユーザーの関連
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings,through: :active_relationships, source: :follower


# 自分がフォローされるユーザーの関連
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers,through: :passive_relationships, source: :following
  # attachmentにはカラム名から_idを除いた名前を記述する
  attachment :profile_image




# https://teratail.com/questions/84523 参考
  validates :name, length: {in: 2..20}
  validates :introduction, length: { maximum: 50 }

  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end

  def self.search(search, word)
        # 完全一致
        if word == "完全一致"
        @users = self.where(name: search)
        # 前方一致
        elsif word == "前方一致"
        @users = self.where("name LIKE ?","#{search}%")
        # 後方一致
        elsif word == "後方一致"
        @users = self.where("name LIKE ?","%#{search}")
        # 部分一致
        elsif word == "部分一致"
        @users = self.where("name LIKE ?","%#{search}%")
        else
        @users = self.all
        end
  end

  # 郵便番号での住所予測変換機能実装
  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
# https://qiita.com/hirokihello/items/a1ddf68d35f3cb7f2779 (名前でログイン)
	 before_action :configure_permitted_parameters, if: :devise_controller?
  	 before_action :authenticate_user!
	def show
		user = current_user
		@book = Book.new
		@user = User.find(params[:id])
		@books = @user.books
	end

	def index
		@users = User.page(params[:page]).reverse_order
		@book = Book.new
	end

	def edit
		@user = User.find(params[:id])
		# 下記の記述があるとif文の中の同じ記述の意味がなくなってしまう
		# @user.id = current_user.id
# もし@userがcurrent_userじゃ無い場合はリダイレクトするようにする
		if @user.id != current_user.id
			redirect_to user_path(current_user)
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] ="You have updated user successfully."
		redirect_to user_path
		else
			render :edit
		end
	end



	def follows
		@user = User.find(params[:id])
		
	end

	def followers
		user = User.find(params[:id])
		@users = user.followers
	end



	protected

	def configure_permitted_parameters
	   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	end

	private
	def user_params
		params.require(:user).permit(:name,:profile_image,:introduction)
 	end
 	# https://pikawaka.com/rails/before_action
 	def redirect_root
    redirect_to root_path unless user_signed_in?
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_map.html.erb
<% if user == current_user %>
<h1>Your Map</h1>

	<div id="map"></div>

	<script>
	function initMap(latlng){
	  var map = new google.maps.Map(document.getElementById('map'), {
	    center: latlng,
	    zoom: 16
	  });

	  var marker = new google.maps.Marker({
	    position: latlng,
	    map: map
	  });
	}

	function getLatLng() {
	  var geocoder = new google.maps.Geocoder();

	  geocoder.geocode({
	    address: "<%= user.prefecture_name %><%= user.address_city %><%= user.address_street %>"
	  }, function(results, status) {
	    if (status == google.maps.GeocoderStatus.OK) {
	      for (var i in results) {
	        if (results[i].geometry) {
	          var latlng = results[i].geometry.location;
	          initMap(latlng)
	        }
	      }
	    }
	  });
	}
	</script>
	<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLEMAP_KEY'] %>&callback=getLatLng" async defer></script>
<% end %>

app/views/users/_mypage&post.html.erb
<!-- userのshowとbooksのnew -->

<%= render 'layouts/error_messages'%>
<div class="templete">


	<!-- ユーザー情報 -->
	<h1>User info</h1>
	<table class="table table-striped">
		<thead>
			<tr>
				<%= attachment_image_tag user, :profile_image,:fill, 100 ,100,format: "jpeg", fallback:"no_image.jpg" %>
			</tr>
			<tr>
				<th>name</th>
				<th><%= user.name %></th>
			</tr>
			<tr>
				<th>introduction</th>
				<th><%= user.introduction %></th>
			</tr>
			<tr>
				<th>
					<%= "フォロー" %>
				</th>
				<th>
					<%= link_to "#{user.followings.count}人",follows_user_path(user.id) %>
				</th>
			</tr>
			<tr>
				<th>
					<%= "フォロワー" %>
				</th>
				<th>
					<%= link_to "#{user.followers.count}人",followers_user_path(user.id) %>
				</th>
			</tr>
			<%if current_user != user %>
			<tr>
				<th>
					<% if user.followed_by?(current_user) %>
					<p><%= link_to "フォローを外す", user_relationships_path(user.id),method: :delete,class: "btn btn-default user-edit-btn" %></p>
					<% else %>
					<p><%= link_to "フォローする",user_relationships_path(user.id),method: :post,class: "btn btn-default user-edit-btn" %></p>
				</th>
			</tr>
			<% end %>
			<% end %>
		</thead>
	</table>


	<!-- http://blog.livedoor.jp/tomoyayoshikawa1022/archives/3681078.html ロゴをボタンに -->
	<% if user.id == current_user.id %>
	<%= link_to edit_user_path(user),class: "btn btn-default user-edit-btn" do %>
	<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
	<% end %>
	<% end %>



	<!-- ここから新規投稿部分 -->
	<h1>New book</h1>
	<!-- form_for部分(@bookは=Book.new) -->
	<form action="/books" method="post"  >
		<!-- 下記の記述が無いとcreateが作動しなかった -->
		<input type="hidden" name="authenticity_token">

		<div>
			<h4>Title</h4>
			<input type="text" id="book_title" name="book[title]" >
		</div>

		<div>
			<h4>Opinion</h4>
			<textarea id="book_body" name="book[body]" ></textarea><br>
		</div>

		<!-- ボタン全体を青色に。classの後は=ではなく：なので注意 -->
		<div class="buttom">
			<input type="submit" name="commit">
		</div>
	</form>

</div>

app/views/users/edit.html.erb
<div class="user-edit">

<%= render 'layouts/error_messages2'%>


<h1>User info</h1>
<form  accept-charset="UTF-8" action="/users/<%=current_user.id%>" method="post">
	<input name="utf-8" type="hidden"value="" >
	<input type="hidden" name="_method" value="PUT">
	<input type="hidden" name="authenticity_token">
<h3>Name</h3>
<input type="text" name="user[name]" value="<%=@user.name%>">

<h3>Image</h3>
<input type="file" name="user[profile_image_id]" %>

<h3>Introduction</h3>
<div>
<textarea name="user[introduction]" ><%=@user.introduction %></textarea><br>
</div>
<input type="submit" name="commit" value="Update User" ata-disable-with="Update User">
</form>
</div>

app/views/users/followers.html.erb
<h1>フォロワー</h1>

<table class="table table-striped">
	<thead>
		<tr>
			<th>ユーザー一覧</th>
		</tr>
	</thead>

	<tbody>
<!--  変数bookを使ってtitle,bodyを以下で表示  -->
		<% @users.each do |user| %>
		<tr>
			<td>
				<%if current_user != user %>
					<% if user.followed_by?(current_user) %>
						<p><%= link_to "フォローを外す", user_relationships_path(user.id),method: :delete %></p>
					<% else %>
						<p><%= link_to "フォローする",user_relationships_path(user.id),method: :post %></p> %>
					<% end %>
				<% end %>
 			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/users/follows.html.erb
<h1>フォロー中のユーザー一覧</h1>

<table class="table table-striped">
	<thead>
		<tr>
			<th>ユーザー名</th>
		</tr>
	</thead>

	<tbody>
<!--  変数bookを使ってtitle,bodyを以下で表示  -->
		<% @user.followings.each do |user| %>
		<tr>
			<td>
				<%= attachment_image_tag user, :profile_image, size: 50, fallback:"no_image.jpg"%>
				-------
				<%= user.name %>
				-------
 			</td>
			<td>
				<%if current_user != user %>
					<% if user.followed_by?(current_user) %>
						<p><%= link_to "フォローを外す", user_relationships_path(user.id),method: :delete %></p>
					<% else %>
						<p><%= link_to "フォローする",user_relationships_path(user.id),method: :post %></p>
					<% end %>
				<% end %>
 			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		 <div class="col-xs-3">
<%= render 'users/mypage&post', {user: current_user,users: @users,book: @book} %>
		 </div>
<div class="col-xs-9">
		<!-- clearfixは不要 -->
<div class="main">
<h1>Users</h1>
<table class="table table-striped">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
		</tr>
	</thead>

	<tbody>
<!--  変数bookを使ってtitle,bodyを以下で表示  -->
		<% @users.each do |user| %>
		<tr>
			<td>
				<%= attachment_image_tag user, :profile_image, size: 50, fallback:"no_image.jpg"%>
 			</td>
			<td>
				<%= user.name %>
		    </td>

		    <td>
		    	<%= link_to "フォロー数：#{user.followings.count}",follows_user_path(user.id) %>
		    </td>

		    <td>
		    	<%= link_to "フォロワー数：#{user.followers.count}人",followers_user_path(user.id) %>
		    </td>

			<td>
				 <% if current_user != user %>
        			<% if user.followed_by?(current_user) %>
            		<p><%=link_to "フォローを外す", user_relationships_path(user.id), method: :delete %></p>
        			<% else %>
            		<p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        			<% end %>
    			<% end %>
    		</td>
		    <td>
				<%= link_to "Show" ,user_path(user.id) %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= paginate @users,class: "paginate" %>
</div>
</div>
</div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
<p class="message"><%= flash[:notice] %></p>
<% end %>
<div class="container">
 <div class="row">
 	<div class="col-xs-3">
  		<%= render 'users/mypage&post', {user: @user,book: @book} %>
	</div>
	<div class="col-xs-9">
<!-- clearfixは不要 -->
<div class="main">
<h1>Books</h1>

<table class="table table-striped">
<thead>
	<tr>
		<th></th>
		<th>Title</th>
		<th>Opinion</th>
	</tr>
</thead>

<tbody>
<!--  変数bookを使ってtitle,bodyを以下で表示  -->
	<% @books.each do |book| %>
	<tr>
		<td>
			<!-- 下記のbook.userはブロック変数book
			のuser_idで関連づけているユーザーのアイコンを表示 -->
			<%= attachment_image_tag book.user, :profile_image, :fill,50,50, fallback:"no_image.jpg" %>
			</td>
		<td>
			<%= link_to book.title,book_path(book) %>
	    </td>
		<td>
			<%= book.body %>
		</td>
	</tr>
	<% end %>
</tbody>
</table>
</div>
	</div>
	</div>
	<!-- 地図を表示 -->
	<%= render "users/map",user: @user %>

</div>