config/routes.rb
Rails.application.routes.draw do
  get "/search", to:"searches#search", as:"search"
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users, :controllers => {
  	:registrations => "users/registrations"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root :to => "homes#top"
get "home/about" => "homes#about"

resources :books do
	resources :books_comments,only: [:create,:destroy,:edit,:update]
	resource :favorites,only: [:create,:destroy]
end
resources :users do
	resource :relationships, only: [:create,:destroy]
	# 下記の２行はいつも通りの記述でも可
	get :follows, on: :member
	get :followers, on: :member
end

end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	attachment :profile_image
	has_many :books_comments,dependent: :destroy
	has_many :favorites,dependent: :destroy

	validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }

    # 解説はメモしている
    def favorite_by?(user)
    	favorites.where(user_id: user.id).exists?
    end

    def self.search(search, word)
    # 完全一致
        if word == "完全一致"
        @books = self.where(title: search)
        # 前方一致
        elsif word == "前方一致"
        @books = self.where("title LIKE ?","#{search}%")
        # 後方一致
        elsif word == "後方一致"
        @books = self.where("title LIKE ?","%#{search}")
        # 部分一致
        elsif word == "部分一致"
        @books = self.where("title LIKE ?","%#{search}%")
        else
        @books = self.all
        end
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!


	def create
		@book = Book.new(book_params)
		# 下記の行がないとuser_idが空になるためエラーが出るので注意
		@book.user_id = current_user.id

		if @book.save(book_params)
			flash[:notice] ="You have created book successfully."
		redirect_to book_path(@book.id)
		else
			# render先に@bookがないというエラーが出るため下記を追加
			@books = Book..page(params[:page]).reverse_order
			render :index
		end
	end

	def index
		@books = Book.page(params[:page]).reverse_order
		@book = Book.new
		@user = User.find(1)
	end

	def show
		@book = Book.find(params[:id])
		@new = Book.new
		# アソシエーションした時に使える記述。@bookからユーザを特定できる
		@user = @book.user
		@books_comment = BooksComment.new

	end

	def edit
		@book = Book.find(params[:id])
		# =で結ぶ際は左右のデータ型が同じで無いといけない。
		if @book.user_id != current_user.id
		   redirect_to books_path
		end
	end

	def update
		@book = Book.find(params[:id])
		@book.user_id = current_user.id
		if @book.update(book_params)
			flash[:notice] ="You have updated book successfully."
		redirect_to book_path(@book.id)
		else
			render :edit
		end
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
	end

	private
	def book_params
		params.require(:book).permit(:title, :body)
	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_books_index.html.erb
<tr>
	<td>
		<!-- 下記のbook.userはブロック変数book
			のuser_idで関連づけているユーザーのアイコンを表示 -->
			<%= link_to user_path(book.user) do %>
			<%= attachment_image_tag book.user, :profile_image, size:50, fallback:"no_image.jpg" %>
			<% end %>
		</td>
		<td>
			<%= link_to book.title,book_path(book) %>
		</td>
		<td>
			<%= book.body %>
		</td>
		<td>
			<!-- いいね機能呼び出し -->
			<span id="favorite-<%= book.id %>">
			<%= render "favorites/favorite",book: book %>
			</span>

		</td>
		<td>
			<%= link_to "コメント数：#{book.books_comments.count}",book_path(book.id) %>
		</td>
		<td>
			<% if current_user != book.user %>
			<% if book.user.followed_by?(current_user) %>
			<p><%= link_to "フォローを外す",user_relationships_path(book.user.id),method: :delete %></p>
			<% else %>
			<p><%= link_to "フォローする", user_relationships_path(book.user.id),method: :post %></p>
			<% end %>
			<% end %>
		</td>
	</tr>

app/views/books/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>



<div class="book-edit">
<h1>Editing Book</h1>

<form  accept-charset="UTF-8" action="/books/<%=@book.id%>" method="post">
	<input name="utf-8" type="hidden" name="utf-8" value="" >
	<input type="hidden" name="_method" value="PUT">
	<input type="hidden" name="authenticity_token">
<%= render 'layouts/error_messages'%>
<div>
<h4>Title</h4>
<input  class="edit-form" type="text" name="book[title]" id="book_title" value="<%=@book.title %>">
</div>

<div>
<h4>Opinion</h4>
<textarea class="edit-form" name="book[body]" id="book_body" ><%=@book.body %></textarea><br>
</div>

<button class="btn btn-primary book-edit-btn">
	<input class="btn btn-primary book-edit-btn" type="submit" name="commit" value="Update Book" data-disable-with="Update Book" >
</button><br>
</form>




<%= link_to "Show" ,book_path %>
<%="|"%>
<%= link_to "Back" ,books_path %>


</div>
</body>
</html>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
					<div class="col-xs-3">
					<%= render 'users/mypage&post', {user: current_user,books: @books,book: @book} %>
					</div>
<div class="col-xs-9">
	<!-- clearfixは不要 -->
<h1>Books</h1>

<table class="table table-striped">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th></th>
			<th></th>
		</tr>
	</thead>

	<tbody>
<!--  変数bookを使ってtitle,bodyを以下で表示  -->
		<% @books.each do |book| %>
		<%= render "books/books_index",book: book %>
		<% end %>
	</tbody>
</table>
		<%= paginate @books,class: "paginate" %>
</div>
</div>
</div>

app/views/books/new.html.erb
<!-- ユーザー情報 -->
<h1>User info</h1>
<%= attachment_image_tag @user, :profile_image,:fill, 60 ,60,format: "jpeg", fallback:"no_image.jpg" %>
<p>name<%= @user.name %></p>
<p>introduction<%= @user.introduction %></p>
<% if @user.id == current_user.id %>
	<p><%= link_to "編集ボタン",edit_user_path(@user) %></p>
<% end %>
<!-- ここから新規投稿部分 -->
<h1>New book</h1>
<!-- form_for部分(@bookは=Book.new) -->
<%= form_for(@book) do |f| %>

<!-- render入れる -->


<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<br><%= f.submit "Create Book" %></br>

<% end %>

app/views/books/show.html.erb
	<body>
		<% if flash[:notice] %>
			<p class="message"><%= flash[:notice] %></p>
		<% end %>

	<div class="container">
	<div class="row">
		<div class="col-xs-3">
		<%= render 'users/mypage&post', {user: @user,book: @new} %>
		</div>
	<div class="col-xs-9">
	<!-- clearfixは不要 -->
	<div class="main">
	<h1>Book detail</h1>

	<table class="table table-striped">
	<thead>
		<tr>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td>
				<!-- https://qiita.com/ezawa800/items/3f18961e043afcb2cf73　画像にリンク -->
				<%= link_to user_path(@user) do %>
				<%= attachment_image_tag @book.user, :profile_image, :fill,100,100, fallback:"no_image.jpg" %><br>
				<% end %>
				<%= link_to @user.name,user_path(@user) %>


				<span id="favorite-<%= @book.id %>">
					<%= render "favorites/favorite",book: @book %>
				</span>


				</td>
			<td>
				<%= @book.title %>
		    </td>
			<td>
				<%= @book.body %>
			</td>
			<!-- もし@bookのユーザーがログインユーザーならボタンを表示 -->
			 <% if @book.user == current_user %>
			<td>
				<%= link_to "Edit" ,edit_book_path,class: "btn btn-success"%>
			</td>
			<td>
				<%= link_to "Destroy" ,book_path(@book),method: :delete,"data-confirm" => "本当に消しますか？",class: "btn btn-danger"%>
			</td>
			 <% end %>
		</tr>
	</tbody>
	</table>

	<!-- コメント機能追加 -->
	<div class="comment-area">
	<h3 class="comment-count"><%= @book.books_comments.count %>件のコメント</h3>
	<table class="table table-striped">
	<thead>
		<tr>
			<th>ユーザー名</th>
			<th>コメント</th>
		</tr>
	</thead>
	<tbody id="comment_ichiran">

			 <!-- コメント一覧呼び出し -->
					<%= render "books_comments/comment_index",book: @book %>

	</tbody>
	</table>
<!-- コメント機能の非同期通信 -->
	<div id="comment-form">
		<%= render "books_comments/comment_form",book: @book,books_comment: @books_comment %>
	</div>


	<table class="table table-striped">
	<thead>
		<tr>
			<th>いいねしたユーザー</th>
		</tr>
	</thead>
	<tbody>
			 <% @book.favorites.each do |favo| %>
		<tr>
			 <td class="favorite-user-name">
			 	<%= favo.user.name %>
			 </td>

			 <% end %>
		</tr>
	</tbody>
	</table>
			</div>
			</div>
		</div>
	</div>
	</body>